src/config/urls.py
"""config URL Configuration

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/3.2/topics/http/urls/
Examples:
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  path('', Home.as_view(), name='home')
Including another URLconf
    1. Import the include() function: from django.urls import include, path
    2. Add a URL to urlpatterns:  path('blog/', include('blog.urls'))
"""
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.views.decorators.cache import never_cache
from django.views.static import serve


from config import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('authentication.urls')),
    path('product/', include('product.urls')),
 
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, view=never_cache(serve))

src/product/urls.py
from django.urls import path, include
from product import views

urlpatterns = [
    path('', views.home_view, name='home'),
    path('search', views.search_view, name='search'),
    path('add/', views.add_product_view, name='add'),
    path('edit/<int:pk>', views.edit_product, name='edit')
]

src/product/models.py
from django.db import models


# Create your models here.
class Variant(models.Model):
    title = models.CharField(max_length=40)
    description = models.TextField()
    active = models.BooleanField(default=True)
   
    def __str__(self):
        return self.title


class Product(models.Model):
    title = models.CharField(max_length=255)
    sku = models.SlugField(max_length=255)
    description = models.TextField()
    def __str__(self):
        return self.title


class ProductImage(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    file_path = models.ImageField( upload_to='product/', null=True, blank=True)


class ProductVariant(models.Model):
    variant_title = models.CharField(max_length=255)
    variant = models.ForeignKey(Variant, on_delete=models.CASCADE)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    
    def __str__(self):
        return self.variant.title


class ProductVariantPrice(models.Model):
    product_variant_one = models.ForeignKey(ProductVariant, on_delete=models.CASCADE,
                                            related_name='product_variant_one')
    product_variant_two = models.ForeignKey(ProductVariant, on_delete=models.CASCADE,
                                            related_name='product_variant_two')
    product_variant_three = models.ForeignKey(ProductVariant, on_delete=models.CASCADE,
                                              related_name='product_variant_three')
    price = models.FloatField()
    stock = models.FloatField()
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    
    def __str__(self):
        return str(self.id)

src/product/forms.py
from django import forms
from product import models

class productForm(forms.ModelForm):
    class Meta(object):
        model = models.Product
        fields = ['sku', 'description', 'title']
        
class ProductImageForm(forms.ModelForm):
    class Meta(object):
        model = models.ProductImage
        fields = ['file_path']
        
class ProductVariantPriceForm(forms.ModelForm):
    class Meta(object):
        model = models.ProductVariantPrice
        fields = ['product_variant_one','product_variant_two','product_variant_three','price','stock']
        

src/product/views.py
from django.shortcuts import render,redirect
from product import models
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.forms import inlineformset_factory
from product import forms
from django.contrib import messages


# Create your views here.
def home_view(request):
   
    products=models.Product.objects.all()
    product_num = products.count()
   
    variant = models.Variant.objects.all()
    
  
    page = request.GET.get('page', 1)
    paginator = Paginator(products, 2)
    try:
        products = paginator.page(page)
    except PageNotAnInteger:
        products = paginator.page(1)
    except EmptyPage:
        products = paginator.page(paginator.num_pages)
    context={
        'products':products,
        'product_num':product_num,
        'variant':variant
    }
    return render(request, 'home.html',context)

# search bar 
def search_view(request):
    if request.method == 'GET':
        search = request.GET.get('inputTitle') 
        dropdown = request.GET.get('dropdown')
        priceFrom = request.GET.get('from') 
        priceTo = request.GET.get('to')
      
        if (priceFrom !=''):
            priceFrom = int(priceFrom)
        else:
            priceFrom = 0
        if (priceTo !=''):
            priceTo = int(priceTo)
        else:
            priceTo = 9999999
       
        searchItem = models.Product.objects.filter(productvariantprice__price__gte = priceFrom, productvariantprice__price__lte = priceTo).filter(title__contains = search).filter(productvariant__variant__title = dropdown)
        context = {
            'products':searchItem,
        }
    return render(request, 'search.html', context)

# add product page 
def add_product_view(request):
    productForm = forms.productForm
    ProductImageForm = forms.ProductImageForm
  
    ProductFormSet = inlineformset_factory(models.Product, models.ProductVariantPrice,
                                        fk_name='product',
                                        fields=('product_variant_one','product_variant_two','product_variant_three','price','stock'),
                                        extra=2)
    formset = ProductFormSet()
    if request.method=='POST':
        productForm = forms.productForm(request.POST, request.FILES)
       
        formset = ProductFormSet(request.POST, request.FILES)
      
        if productForm.is_valid() and formset.is_valid():
            product=productForm.save()
            pd=formset.save(commit=False)
            for p in pd:
                p.product=product
                p.save()
       
            messages.success(request, f"Product has been added")
            return redirect('home')
    context={
        'productForm':productForm,
        'ProductImageForm' : ProductImageForm,
        'formset':formset,
    }
    return render(request, 'product_add.html', context)


def edit_product(request, pk):
   
    product = models.Product.objects.get(id=pk)
    productForm = forms.productForm(instance=product)
    
  
    BookFormSet = inlineformset_factory(models.Product, models.ProductVariantPrice,
                                        fk_name='product',
                                        fields=('product_variant_one','product_variant_two','product_variant_three','price','stock'),
                                        extra=2)
    formset = BookFormSet(instance=product)
    
    if request.method=='POST':
        productForm = forms.productForm( request.POST, request.FILES, instance=product)
        formset = BookFormSet(request.POST, request.FILES, instance=product)
        if productForm.is_valid() and formset.is_valid():
            productForm.save()
            formset.save(commit=False)
            formset.instance=product
            formset.save()
         
            messages.success(request, f"Product has been updated")
            return redirect('home')
    context={
        'productForm':productForm,
        'formset':formset,
        
    }
    return render(request, 'edit_product.html',context)

src/product/templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <link
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css"
      rel="stylesheet"
      integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3"
      crossorigin="anonymous"
    />
 
    <link
      rel="stylesheet"
      href="https://use.fontawesome.com/releases/v5.15.4/css/all.css"
      integrity="sha384-DyZ88mC6Up2uqS4h/KRgHuoeGwBcD4Ng9SiP4dIRy0EXTlnuz47vAwmeGwVChigm"
      crossorigin="anonymous"
    />

  </head>
  <body class="bodycolor">

    <nav
      class="navbar navbar-expand-lg fixed-top shadow rounded-bottom"
      style="background: white;"
    >
      <div class="container-fluid">
        <a class="navbar-brand brandcolor ms-5" href="/">MediusWare</a>
        <button
          class="navbar-toggler custom-toggler"
          type="button"
          data-bs-toggle="collapse"
          data-bs-target="#navbarSupportedContent"
          aria-controls="navbarSupportedContent"
          aria-expanded="false"
          aria-label="Toggle navigation"
        >
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav me-auto mb-2 mb-lg-0">
            <li class="nav-item me-2 mb-lg-0 mb-3">
              <a class="btn textColor" aria-current="page" href="#">abc</a>
            </li>
            <li class="nav-item me-2 mb-lg-0 mb-3">
              <a class="btn textColor" aria-current="page" href="#">adg</a>
            </li>
            <li class="nav-item me-2 mb-lg-0 mb-3">
              <a class="btn textColor" aria-current="page" href="#">ads</a>
            </li>
          </ul>
        </div>
      </div>
    </nav>


    <div style="text-align: center">
      {% if messages %}
      <br /><br /><br />
      {% for msg in messages %}
      <div class="alert alert-{{msg.tags}}">{{msg}}</div>
      {% endfor %} {% endif %}
    </div>
    <br /><br /><br />
    <!-- content  -->
    <div style="min-height: 100vh;">{% block content %} {% endblock %}</div>

    <!-- Footer -->
    <br /><br /><br />
    <footer class="footerHeader">
      <br /><br />
      <div class="container">
        <div class="row text-center textColor">
          <p>Copyright &copy: Mediusware 2021</p>
        </div>
        <br /><br /><br /><br /><br /><br />
      </div>
    </footer>
    <!-- prism js for systax highlighter  -->
    <!-- <script src="{% static 'js/prismokd.js' %}" ></script> -->

    <!-- custom js  -->
    <!-- <script src="{% static 'js/index.js' %}"></script> -->

    <!-- bootstrap JS -->
    <script
      src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.10.2/dist/umd/popper.min.js"
      integrity="sha384-7+zCNj/IqJ95wo16oMtfsKbZ9ccEh31eOz1HGyDuCQ6wgnyJNSYdrPa03rtR1zdB"
      crossorigin="anonymous"
    ></script>
    <script
      src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.min.js"
      integrity="sha384-QJHtvGhmr9XOIpI6YVutG+2QOK9T+ZnN4kzFN1RtK3zEFEIsxhlmWl5/YESvpZ13"
      crossorigin="anonymous"
    ></script>
  </body>
</html>

src/product/templates/edit_product.html
{% extends 'base.html' %} {% load widget_tweaks %} {% block content %}
<head>
    <!-- dropzon css for drag and drop image  -->
    <link rel="stylesheet" href="https://rawgit.com/enyo/dropzone/master/dist/dropzone.css">
</head>
<div class="container">
    <br><br>
    <form method="POST" autocomplete="off" enctype="multipart/form-data" class="">
   
        <div class="row">
            <h4>Update Product</h4>
            <!-- left side  -->
            <div class="col-md-6">
                <div class="shadow p-3">
                <!-- product part  -->
                {% for field in productForm %}
                <p>
                    <!-- level & textarea -->
                    {{ field.label_tag }}<br>
                    <div class="form-group">
                      {% render_field field|attr:'required:true'  class="form-control item" %}
                    </div>
                    <!-- help text or suggestions -->
                    {% if field.help_text %}
                      <small style="color: grey">{{ field.help_text }}</small>
                    {% endif %}
          
                    <!-- Error message -->
                    {% for error in field.errors %}
                      <p style="color: red">{{ error }}</p>
                    {% endfor %}
                  </p>
                  {% endfor %}
                </div>
                <br>

                  <!-- image field  -->
                  <div class="shadow p-3" >
                      <h3>Media</h3>
                      <div class="fallback dropzone">
                        <input name="file" type="file" multiple />
                      </div>
                  </div>
            </div>
            <!-- right side  -->
            <div class="col-md-6 shadow">
               
              <div>
                {{formset.as_p}}
              </div>
              
            </div>
            <br><br>
            <div class="row">
              <div class="col-md-3 m-3">
                <button class="btn btn-primary" type="submit">Save</button>
              <a href="/" class="btn btn-secondary" >Cancel</a>
              </div>
            </div>
            
            <br> <br>
        
    </div>
  </form>
    <!-- dropzone js  -->
    <script src="https://rawgit.com/enyo/dropzone/master/dist/dropzone.js"></script>
</div>
{% endblock %}

src/product/templates/home.html
{% extends 'base.html' %} {% block content %}
<br><br>
<div class="container">
    <div class="row">
        <h3 class="table-title text-primary "> <a href="add" class="text-decoration-none">Add Products</a> </h3>
    </div>
    <div class="row d-flex justify-content-center">
        <form class="d-flex" method="get" action="/search">
       
            <div class="col-md-2 me-auto">
            <input
              class="form-control"
              type="search"
              placeholder="Product Title"
              aria-label="Search"
              name="inputTitle"
            />
        </div>
        <div class="col-md-2 m-auto dropdown ">
       
              <select name="dropdown" class="custom-select btn btn-outline-secondary"
			style="width:150px;">
            {% for v in variant %}
		    <option value="{{v}}">{{v}}</option>
		  
            {% endfor %}
	</select>
        </div>
        <div class="col-md-3 m-auto">
            <div class="row">
                <div class="input-group">
                    <div class="input-group-text" id="btnGroupAddon">Price Range</div>
                    <input name="from" type="number" class="form-control" placeholder="From" aria-label="Input group example" aria-describedby="btnGroupAddon">
                    <input name="to" type="number" class="form-control" placeholder="To" aria-label="Input group example" aria-describedby="btnGroupAddon">
                  </div>
            </div>
        </div>
        <div class="col-md-1 m-auto">date</div>
            <button class="btn btn-primary" type="submit"><i class="fas fa-search"></i></button>
          </form>
        
    </div>
    <br>

    <div class="row">
        <div class="col-md-12 table-responsive border-primary">
            <table class="table table-bordered table-striped text-center table-hover">
                
                <div class="row" style="text-align: left;">
                        <div class="col-md-1"> <b>#</b></div>
                        <div class="col-md-2"><b>Title</b> </div>
                        <div class="col-md-4"> <b>Description</b> </div>
                        <div class="col-md-4"> <b>variant</b> </div>
                        <div class="col-md-1"> <b>Action</b> </div>
                        <hr>
                </div>

                <div class="row" style="text-align: left;">
                    {% for product in products %}
                        <div class="col-md-1">{{forloop.counter}}</div>
                        <div class="col-md-2">{{product.title}}</div>
                        <div class="col-md-4">{{product.description}}</div>
                        <!-- backward filter from parent to child  -->
                        
                        <div class="col-md-4">
                            <div class="row">
                                {% for p in product.productvariantprice_set.all %}
                                <div class="col-md-4">{{p.product_variant_one.variant}}/{{p.product_variant_two.variant}}/{{p.product_variant_three.variant}}</div>
                                <div class="col-md-4">Price: {{p.price}}</div>
                                <div class="col-md-4">InStock: {{p.stock}}</div>
                                {% endfor %}
                            </div>
                        </div>
                        
                        <div class="col-md-1"><a href="edit/{{product.id}}" class="btn btn-success">Edit</a></div>
                        <hr>
                        {% endfor %}
                </div>
                
            </table>
        </div>
    </div>
    <br> <br>
</div>

<!-- for paginators  -->
<div class="container">
    <div class="row">
      <div class="col-md-6">
        Showing {{products.start_index }} to {{products.end_index }} out of
        {{product_num}}
      </div>

      <div class="col-md-6" style="display: flex; justify-content: end">
          {% if products.has_other_pages %}
          <div class="btn-group me-2" role="group" aria-label="First group">
            {% if products.has_previous %}
            <button type="button" class="btn btn-outline-primary"><a href="?page={{ products.previous_page_number }}">&laquo;</a></button>
              
            
            {% else %}
            <button type="button" class="btn btn-outline-primary disabled"><span>&laquo;</span></button>
            {% endif %} 
            {% for i in products.paginator.page_range %} 
            {% if products.number == i %}
            <button type="button" class="btn btn-outline-primary active">{{ i }}<span class="sr-only">(current)</span></button>
            {% else %}
            <button type="button" class="btn btn-outline-primary"><a href="?page={{ i }}" class="p-2">{{ i }}</a></button>
            {% endif %} 
            {% endfor %} 
            {% if products.has_next %}
            <button type="button" class="btn btn-outline-primary"><a href="?page={{ products.next_page_number }}">&raquo;</a></button>
            {% else %}
            <button type="button" class="btn btn-outline-primary disabled"><span>&raquo;</span></button>
            {% endif %}
        </div>
          {% endif %}
        </div>
    </div>
  </div>
{% endblock %}

src/product/templates/product_add.html
{% extends 'base.html' %} {% load widget_tweaks %} {% block content %}
<head>
    <!-- dropzon css for drag and drop image  -->
    <link rel="stylesheet" href="https://rawgit.com/enyo/dropzone/master/dist/dropzone.css">
</head>
<div class="container">
    <br><br>
    <form method="POST" autocomplete="off" enctype="multipart/form-data" class="">
     
    <div class="row">
            <h4>Create Product</h4>
            <!-- left side  -->
            <div class="col-md-6">
                <div class="shadow p-3">
                <!-- product part  -->
                {% for field in productForm %}
                <p>
                    <!-- level & textarea -->
                    {{ field.label_tag }}<br>
                    <div class="form-group">
                      {% render_field field|attr:'required:false'  class="form-control item" %}
                    </div>
                    <!-- help text or suggestions -->
                    {% if field.help_text %}
                      <small style="color: grey">{{ field.help_text }}</small>
                    {% endif %}
          
                    <!-- Error message -->
                    {% for error in field.errors %}
                      <p style="color: red">{{ error }}</p>
                    {% endfor %}
                  </p>
                  {% endfor %}
                </div>
                <br>

                  <!-- image field  -->
                  <div class="shadow p-3" >
                      <h3>Media</h3>
                      <div class="fallback dropzone">
                        <input name="file" type="file" multiple />
                      </div>
                  </div>
            </div>
            <!-- right side  -->
            <div class="col-md-6 shadow">
              <div>
                {{formset.as_p}}
              </div>
            </div>
            <br><br>
            <div class="row">
              <div class="col-md-3 m-3">
                <button class="btn btn-primary" type="submit">Save</button>
              <a href="/" class="btn btn-secondary" >Cancel</a>
              </div>
            </div>
            
            <br> <br>
        
    </div>
  </form>
    <!-- dropzone js  -->
    <script src="https://rawgit.com/enyo/dropzone/master/dist/dropzone.js"></script>
</div>
{% endblock %}

src/product/templates/search.html
{% extends 'base.html' %} {% block content %}
<div class="container">
    <br><br><br>
    <div class="row"><h2 class="text-center">Search result</h2></div>
    <br>
    <div class="row" style="text-align: left;">
        {% for product in products %}
            <div class="col-md-1">{{forloop.counter}}</div>
            <div class="col-md-2">{{product.title}}</div>
            <div class="col-md-4">{{product.description}}</div>
            <!-- backward filter from parent to child  -->
            
            <div class="col-md-4">
                <div class="row">
                    {% for p in product.productvariantprice_set.all %}
                    <div class="col-md-4">{{p.product_variant_one.variant}}/{{p.product_variant_two.variant}}/{{p.product_variant_three.variant}}</div>
                    <div class="col-md-4">Price: {{p.price}}</div>
                    <div class="col-md-4">InStock: {{p.stock}}</div>
                    {% endfor %}
                </div>
            </div>
            
            <div class="col-md-1"><a href="#" class="btn btn-success">Edit</a></div>
            <hr>
            {% endfor %}
    </div>
    
</table>
</div>
</div>
<br> <br>
</div>
{% endblock %}